### ISSUE TITLE
$_SERVER['REQUEST_SCHEME'] not available for Apache 2.2 or LiteSpeed

### ISSUE THREAD

**Issue by krizzzly** [bitboxde/error-notifier#1]
https://github.com/bitboxde/error-notifier/blob/350f9187bf3df8b37fec2101340bb5bd3ba9d102/src/templates/mail/exception.html#L34

It throws an '500 Internal Server Error' for LiteSpeed Webserver or Apache 2.2
You could use `$_SERVER['HTTPS']`. It returns e.g. `'on'`

**Comment by bitboxfw** [comment]
Fixed with version 1.0.4
